---
abstract: 'Basic, Protocol-level BitTorrent Utilities'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Carp: 0
  Exporter: 0
  Module::Build: 0.38
  Test::More: 0
  perl: v5.10.0
configure_requires:
  File::Find: 0
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
keywords:
  - BitTorrent
  - Protocol
  - Packet
  - Utility
  - Bencode
  - Compact
  - Peers
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-BitTorrent-Protocol
provides:
  Net::BitTorrent::Protocol:
    file: lib/Net/BitTorrent/Protocol.pm
    version: v0.9.1
  Net::BitTorrent::Protocol::BEP03:
    file: lib/Net/BitTorrent/Protocol/BEP03.pm
    version: v0.9.1
  Net::BitTorrent::Protocol::BEP03::Bencode:
    file: lib/Net/BitTorrent/Protocol/BEP03/Bencode.pm
    version: v0.9.0
  Net::BitTorrent::Protocol::BEP05:
    file: lib/Net/BitTorrent/Protocol/BEP05.pm
    version: v0.9.0
  Net::BitTorrent::Protocol::BEP06:
    file: lib/Net/BitTorrent/Protocol/BEP06.pm
    version: v0.9.1
  Net::BitTorrent::Protocol::BEP07:
    file: lib/Net/BitTorrent/Protocol/BEP07.pm
    version: v0.9.0
  Net::BitTorrent::Protocol::BEP10:
    file: lib/Net/BitTorrent/Protocol/BEP10.pm
    version: v0.9.0
  Net::BitTorrent::Protocol::BEP23:
    file: lib/Net/BitTorrent/Protocol/BEP23.pm
    version: v0.9.0
requires:
  Carp: 0
  Exporter: 0
  Module::Build: 0.38
  perl: v5.10.0
resources:
  bugtracker: http://github.com/sanko/net-bittorrent/issues
  homepage: http://sankorobinson.com/net-bittorrent/
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/net-bittorrent-protocol.git
  x_ChangeLog: http://github.com/sanko/net-bittorrent-protocol/commits/
version: v0.9.1
